### PR TITLE
Fix frame positions, improve cutsheet

### PR DESCRIPTION
**Pull request by jonnor**
Now frames are positioned correctly inside the sheeting of the house.
Some parts were missing in the cutsheet,
and nesting server required an external HTTP server for the .jsjob file

### CODE REVIEW

**Comment by jonnor** [comment]
I'll rebase on master to resolve conflict

**Comment by johnrees** [comment]
cool, thanks @jonnor. I've now deactivated codeclimate on PRs (didn't realise it would automatically register/attach itself)

**Comment by jonnor** [comment]
Odd failure on Travis CI, inside JS of a dependency - but only on one of the builds.

```
    /home/travis/build/wikihouseproject/buildx-editor/node_modules/fraction.js/fraction.js:170
    }});
      ^
    SyntaxError: Unexpected token )
      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/ScriptTransformer.js:289:17)
      at Object.<anonymous> (node_modules/mathjs/lib/type/fraction/Fraction.js:1:105)
```

**Comment by johnrees** [comment]
It's related to these issues https://github.com/facebook/jest/issues/1874 https://github.com/facebook/jest/issues/3894 

Maybe jest is causing too many problems at this point :/

**Comment by jonnor** [comment]
@johnrees it passed now. Not much of an issue. Enough bigger fish to fry.

**Comment by jonnor** [comment]
I think this can be merged now?

**Pull request merged**
