### PR TITLE
Switch from WebRTC transport to postMessage

### PR DESCRIPTION
**Pull request by bergie**
screenshot 2017-08-11 at 13 39 13

See also noflo/grunt-noflo-browser#25

### CODE REVIEW

**Comment by johnrees** [comment]
yikes, i screwed push up a bit sorry

**Comment by johnrees** [comment]
screen shot 2017-08-11 at 15 08 48

I updated the components to work with the current version of wren. Not sure if I've done the graph in the 'correct way' though, might be worth checking

**Comment by johnrees** [comment]
I'll try and sort out the commit history here

**Comment by jonnor** [comment]
Thanks for testing and updating, I was just looking at it as well!
There is not much definition of "correct" in this graph for now, it just a most basic demo.
So when the commit history is cleaned, I think this is good to to go master

**Comment by jonnor** [comment]
I found one minor bug in runtime URL creation, fixed on branch `fix-undefined-runtime-id`: https://github.com/wikihouseproject/buildx-editor/commit/e28c90c485687df8b68fddceee666a0b4e3a876b

**Comment by jonnor** [comment]
@johnrees I don't see any problems with the commit history, just that it was rebased on master?

**Comment by johnrees** [comment]
It made a bunch of duplicate commits in the PR, something I hadn't run into before. Seem to have fixed it now, will merge if I haven't screwed anything up.

**Comment by jonnor** [comment]
Ah yes, I see what you meant now. You merged in a branch with rewritten versions of each original commit (probably due to rebase).

**Comment by johnrees** [comment]
Merged, thanks guys 🎉 

@jonnor I rebased your fix into this PR before the merge too.

**Pull request merged**
