### PR TITLE
Initial nesting support using SvgNest

### PR DESCRIPTION
**Pull request by jonnor**
# Work in progress, not intended to be merged

Done

* [x] Use SvgNest as library, taking SVG string input, outputting SVG strings
* [x] Runnable server-side, in PhantomJS via JsJob
* [x] Include custom SvgNest version in git
* [x] Fix loading of worker scripts/code (CORS)
* [x] Send patches upstream
* [x] HTTP API for doing nesting from client-side/other-service

Next
* [ ] Test with Wren outline output
* [ ] Apply transformations to full Wren output
* [ ] Finalize automated test

### CODE REVIEW

**Comment by jonnor** [comment]
SvgNest work currently at https://github.com/jonnor/SVGnest/tree/hack-webpack

**Comment by jonnor** [comment]
I think we'll have to pass the WebWorker code over using a Blob URL. This probably means we need to inline the files needed as a string we can pass in. 
This is primarily because when running under JsJob, a dedicated PhantomJs instance with no external network access or other ability to include scripts (except for packaging into the specified .js).

**Comment by jonnor** [comment]
https://github.com/jdhenke/phantomjs-webworker-example was useful to sanity-check basic WebWorker functionality for PhantomJS

**Comment by jonnor** [comment]
The WebWorker usage in SVGNest is pretty... non-idiomatic. Instead of loading code from the worker script, the code is in the client as seemingly-standard functions and shipped over to the worker via `postMessage` which then `eval()`s it. The functions use a `postMessage` at the bottom to return results.
This is done/abstracted mostly by the `Parallel` class.

**Comment by johnrees** [comment]
@jonnor I've added [jest](https://facebook.github.io/jest/), its syntax is very similar to mocha. You'll see the test file is almost identical https://github.com/wikihouseproject/buildx-editor/pull/4/commits/18f311cb40437e27e89ad0812580d312fd891559#diff-2623c1cdc91e51ba1fe838104ae8a530

If you hate it for some reason let me know and I'll revert to mocha.

I've been using it for the last few projects and really like its interactive watch mode, output, and speed (parallel tests).

Running `jest` (now currently `npm test`) will search for any `./**/__tests__/**/*.js` files in the project and run them in a single output.

I tend to put everything in a single directory, but I quite like the flexibility of this approach for modules like `wren` where its intended to be extracted into its own package once its ready e.g. https://github.com/wikihouseproject/buildx-editor/tree/master/src/lib/wren/__tests__/

**Comment by jonnor** [comment]
The upstream patches for SVGnest are:

https://github.com/Jack000/SVGnest/pull/54
https://github.com/Jack000/SVGnest/pull/53
https://github.com/Jack000/SVGnest/pull/52
https://github.com/Jack000/SVGnest/pull/51

The only thing that is not sent upstream is our a bit hacky way of using inline code instead of `importScript` (a JsJob requirement). Would have to ask maintainer if they are interested in something like that, and how they would like to see it done if soo. https://github.com/wikihouseproject/SVGnest/commit/07342b5b1c833e7124a5c016a21c8a70851bd11e

**Comment by jonnor** [comment]
All the SVGNest pull requests I made were merged today. CC @johnrees

**Pull request merged**
